export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_ONLINE_USER_SUCCESS = "ADD_ONLINE_USER_SUCCESS";
export const ADD_ONLINE_USER_FAILURE = "ADD_ONLINE_USER_FAILURE";

export const DELETE_ONLINE_USER_SUCCESS = "DELETE_ONLINE_USER_SUCCESS";
export const DELETE_ONLINE_USER_FAILURE = "DELETE_ONLINE_USER_FAILURE";
